print('Welcome to the Mad Lib Generator!.')
adjective1 = raw_input('Type in an adjective: ')
adjective2 = raw_input('Type in another adjective: ')
adjective3 = raw_input('Type in a final adjective: ')
adjective4 = raw_input('Type in a final final adjective: ')
animal = raw_input('Type in an animal: ')
verb1 = raw_input('Type in a verb: ')
plural_noun = raw_input('Plural noun: ')
name = raw_input('Name a female musician: ')
beverage = raw_input('Name a drink: ')
body_part = raw_input('Name a body part: ')

print("Excellent choices! Here is your story...")
print("There once was a " + adjective1 + " programmer named " + name)
print("who wanted to build a " + adjective2 + " mobile app to ")
print("help " + adjective3 + " " + animal + " find new homes.")
print("")
print(name + ' stayed up all night, drinking lots of ' + beverage)
print(' caffeinated ' + adjective4 + ' as she worked and worked')
print(' trying to complete her ' + verb1 + ' program.')
print("")
print('Whenever ' + name + ' hit a dead end, she would')
print('exclaim ' + body_part + '!')
print("")
print("But she was not discouraged, and after a quick break ")
print('to ' + adjective1 + ' and clear her head, she got back to work.')
print("")
print('By morning, when the sun started to rise, she let out a big yawn and stretched her' + body_part + 'finally she was done.')
